### PR TITLE
Only: Extends "BoxProps" instead of "GenericProps"

### LINKED ISSUE #246: Property 'flex' does not exist on type OnlyProps
## What:

The props of the `Only` component do not list the `flex` property.

## Why:

Most likely the props `Only` inherits do not have the `flex` key set. I guess `Box` may have that prop as an explicit one, instead of being within the `Flexbox` interface.

## Environment:

- atomic-layout version: `0.10.0`

## Steps to reproduce:

```jsx
import { Only } from 'atomic-layout'

const Example = () => (
  <Only flex alignItems="center">Foo</Only>
)
```

## Expected behavior:

`flex` prop is known and properly typed for the `Only` component.

## Screenshots:

Screenshot 2019-11-06 at 10 54 24

### PR DESCRIPTION
**Pull request by kettanaito**
## Changes

- `Only` component types now extend `BoxProps` instead of `GenericProps`. This allows for `Only` to have Box props like `flex` and `inline` plus all the generic props.

## GitHub

- Closes #246

### CODE REVIEW

File: src/components/Only.tsx [hunk 1]
```diff
@@ -16,7 +15,7 @@ const resolveBreakpoint = (breakpointRef: BreakpointRef): Breakpoint => {
     : breakpointRef
 }
 
-export interface OnlyProps extends GenericProps {
+export interface OnlyProps extends BoxProps {
```
Comment (kettanaito) [inline src/components/Only.tsx]: This is the main change of this pull request.
